# Generated by Django 2.2.4 on 2019-08-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('fname_alumni', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('lname_alumni', models.CharField(max_length=32)),
                ('description_alumni', models.TextField(blank=True, null=True)),
                ('emal_alumni', models.CharField(blank=True, max_length=32, null=True)),
                ('number_alumni', models.CharField(blank=True, max_length=32, null=True)),
                ('github_alumni', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
