# Generated by Django 2.2.4 on 2019-08-11 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name_language', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2016-2017', '2016-2017'), ('2017-2018', '2017-2018'), ('2018-2019', '2018-2019'), ('2019-2020', '2019-2020')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name_project', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description_project', models.TextField(blank=True, null=True)),
                ('picture_project', models.ImageField(blank=True, max_length=50, null=True, upload_to='')),
                ('language_project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kssdasite.Language')),
                ('year_project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kssdasite.Year')),
            ],
        ),
        migrations.AddField(
            model_name='language',
            name='year_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kssdasite.Year'),
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('first_name_alumni', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('last_name_alumni', models.CharField(max_length=32)),
                ('picture_alumni', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('description_alumni', models.TextField(blank=True, null=True)),
                ('email_alumni', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone_number_alumni', models.CharField(blank=True, max_length=32, null=True)),
                ('github_link_alumni', models.URLField(blank=True, null=True)),
                ('cv_alumni', models.FileField(default='', upload_to='docs/')),
                ('project_alumni', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kssdasite.Project')),
            ],
            options={
                'verbose_name_plural': 'Alumni',
            },
        ),
    ]
