# Generated by Django 2.2.4 on 2019-08-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kssdasite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='fname_alumni',
            new_name='first_name_alumni',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='github_alumni',
            new_name='github_link_alumni',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='lname_alumni',
            new_name='last_name_alumni',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='number_alumni',
            new_name='phone_number_alumni',
        ),
    ]
