# Generated by Django 2.2.4 on 2019-08-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kssdasite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumni',
        ),
    ]
