# Generated by Django 2.2.4 on 2019-08-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kssdasite', '0002_auto_20190807_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='emal_alumni',
            new_name='email_alumni',
        ),
    ]
