# Generated by Django 2.2.4 on 2019-08-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kssdasite', '0002_delete_alumni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
