# Generated by Django 2.2.4 on 2019-08-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kssdasite', '0003_delete_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
