# Generated by Django 2.2.4 on 2019-08-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kssdasite', '0004_auto_20190807_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name_project', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description_project', models.TextField(blank=True, null=True)),
                ('picture_project', models.ImageField(blank=True, max_length=50, null=True, upload_to='')),
            ],
        ),
    ]
