# Generated by Django 2.2.4 on 2019-08-14 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kssdasite', '0004_delete_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_language', models.CharField(max_length=50)),
                ('year_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kssdasite.Year')),
            ],
        ),
    ]
