# Generated by Django 2.2.4 on 2019-08-14 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kssdasite', '0005_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=255)),
                ('description_project', models.TextField(blank=True, null=True)),
                ('picture_project', models.ImageField(blank=True, max_length=50, null=True, upload_to='')),
                ('language_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kssdasite.Language')),
            ],
        ),
    ]
