# Generated by Django 2.2.4 on 2019-08-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kssdasite', '0006_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='language_project',
        ),
    ]
