# Generated by Django 2.2.4 on 2019-08-10 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kssdasite', '0006_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={'verbose_name_plural': 'Alumni'},
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name_language', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('year_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kssdasite.Year')),
            ],
        ),
    ]
