# Generated by Django 2.2.4 on 2019-08-11 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kssdasite', '0007_auto_20190810_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language_project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kssdasite.Language'),
        ),
        migrations.AddField(
            model_name='project',
            name='year_project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kssdasite.Year'),
        ),
    ]
