# Generated by Django 2.2.4 on 2019-08-14 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kssdasite', '0007_remove_project_language_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='year_project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kssdasite.Year'),
        ),
    ]
