# Generated by Django 2.2.4 on 2019-08-11 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kssdasite', '0008_auto_20190811_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='cv_alumni',
            field=models.FileField(default='', upload_to='docs/'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='project_alumni',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kssdasite.Project'),
        ),
    ]
