# Generated by Django 2.2.4 on 2019-08-14 11:28

from django.db import migrations, models
import django.db.models.deletion
import kssdasite.models


class Migration(migrations.Migration):

    dependencies = [
        ('kssdasite', '0010_auto_20190814_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture_project',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to=kssdasite.models.upload_location),
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_alumni', models.CharField(max_length=32)),
                ('last_name_alumni', models.CharField(max_length=32)),
                ('picture_alumni', models.ImageField(blank=True, max_length=255, null=True, upload_to=kssdasite.models.upload_location)),
                ('description_alumni', models.TextField(blank=True, null=True)),
                ('email_alumni', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone_number_alumni', models.CharField(blank=True, max_length=32, null=True)),
                ('github_link_alumni', models.URLField(blank=True, null=True)),
                ('cv_alumni', models.FileField(default='', upload_to=kssdasite.models.upload_location)),
                ('project_alumni', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kssdasite.Project')),
            ],
            options={
                'verbose_name_plural': 'Alumni',
            },
        ),
    ]
