# Generated by Django 2.2.4 on 2019-08-15 11:51

from django.db import migrations, models
import kssdasite.models


class Migration(migrations.Migration):

    dependencies = [
        ('kssdasite', '0014_auto_20190815_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='language_alumni',
        ),
        migrations.AlterField(
            model_name='project',
            name='picture_project',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to=kssdasite.models.upload_location),
        ),
    ]
