# Generated by Django 2.2.4 on 2019-08-15 12:01

from django.db import migrations, models
import django.db.models.deletion
import kssdasite.models


class Migration(migrations.Migration):

    dependencies = [
        ('kssdasite', '0022_auto_20190815_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='language_alumni',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='kssdasite.Language'),
        ),
        migrations.AlterField(
            model_name='project',
            name='picture_project',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to=kssdasite.models.upload_location),
        ),
    ]
