# Generated by Django 2.2.4 on 2019-08-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kssdasite', '0023_auto_20190815_1801'),
        ('kssdasite', '0022_auto_20190815_1702'),
    ]

    operations = [
    ]
